## Numpy
operações matemáticas e calculos científicos

- Arrays: coleção de elementos acessiveis por meio de índices. Coleção ordenada de elementos do *MESMO TIPO*

### Criando arrays

In [1]:
import numpy as np

#criando um array através de uma lista
array_from_list = np.array([1, 2, 3, 4])
print(f"Array from list: {array_from_list}")

Array from list: [1 2 3 4]


In [2]:
#mais de uma dimensão

#array de zeros
a_zeros = np.zeros([3, 3])
print("Arrays de zero:")
print(a_zeros)

Arrays de zero:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
a_range = np.arange(0, 10, 2)
print(f"Array from range: {a_range}") #um array no range de 0 a 10 (sendo o 10 não inclusivo), pulando de 2 em 2

Array from range: [0 2 4 6 8]


In [5]:
matriz = np.array([[1.0, 2], [3, 4]]) # matriz 2x2
print(matriz)

[[1. 2.]
 [3. 4.]]


In [7]:
tensor = np.array([[[1,2], [3,4]], [[5,6], [7,8]]]) #um array 2x2 de arrays 2x2
print(tensor)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [8]:
print(matriz.shape)
print(tensor.shape)

(2, 2)
(2, 2, 2)


Operações

In [9]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a + b

print(c)

[5 7 9]


In [10]:
d = a * b
print(d)

[ 4 10 18]


In [11]:
e = b/a
print(e)

[4.  2.5 2. ]


In [1]:
import numpy as np
np.random.rand(2, 3) #MATRIZ DUAS LINHAS E 3 COLUNAS (o rand só gera valores entre 0 e 1)

array([[0.29852795, 0.09489553, 0.66659026],
       [0.99704258, 0.71590702, 0.29095991]])

In [2]:
import numpy as np
np.random.randint(0, 10, size = (2, 3)) #uma matriz 2x3 de numeros no range de inteiros entre 0 e 10 (sendo o 10 não inclusivo)

array([[9, 0, 7],
       [4, 1, 2]])

In [3]:
#indexação

import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]]) #item possui um índice
print(a[0, 0]) # print o item que está na linha e coluna de indice 0
print(a[0, 2]) # print o item que na linha está na posição 0 e na coluna 2
print(a[-1, -1]) #print o item que está na linha e coluna -1 

1
3
6


In [7]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print (a[0:2, 1:3]) #indice 0 a 2 sendo o 0 exclusivo; indice de 1 a 3 sendo o 1 exclusivo e o 3 inclusivo

#operações
print(f"soma = {a.sum()}")
print(f"máximo = {a.max()}")
print(f"mínimo = {a.min()}")
print(f"média = {a.mean()}")
print(f"std = {a.std()}")
print(f"var = {a.var()}")

[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]
soma = 21
máximo = 6
mínimo = 1
média = 3.5
std = 1.707825127659933
var = 2.9166666666666665


In [10]:
#suponha que uma loja venda três tipos de produtos: livros, roupas e eletrônicos. você coleta avaliações para cada tipo de produto em uma escala de 1 a 5 estrelas

#importando biblioteca numpy
import numpy as np

#dados de avaliação
#cada lista contém avaliações de uma escala de 1 a 5 para cada tipo de produto
books = np.array([5, 4, 4, 3, 5, 2, 4, 5])
clothes = np.array([2, 3, 1, 4, 3, 3, 4, 2])
electronics = np.array([3, 5, 4, 4, 5, 2, 3, 5])

# calculo de estatisticas 

#livros
media_books = np.mean(books)
mediana_books = np.median(books)
desvio_books = np.std(books)

#roupas
media_clothes = np.mean(clothes)
mediana_clothes = np.median(clothes)
desvio_clothes = np.std(clothes)

#eletronicos
media_eletro = np.mean(electronics)
mediana_eletro = np.median(electronics)
desvio_eletro = np.std(electronics)

#exibindo resultados
print(f"Livros - Média: {media_books}, Mediana: {mediana_books}, Desvio padrão: {desvio_books}")
print(f"Roupas - Média: {media_clothes}, Mediana: {mediana_clothes}, Desvio padrão: {desvio_clothes}")
print(f"Eletrônicos - Média: {media_eletro}, Mediana: {mediana_eletro}, Desvio padrão: {desvio_eletro}")

Livros - Média: 4.0, Mediana: 4.0, Desvio padrão: 1.0
Roupas - Média: 2.75, Mediana: 3.0, Desvio padrão: 0.9682458365518543
Eletrônicos - Média: 3.875, Mediana: 4.0, Desvio padrão: 1.0532687216470449


# Pandas
## Pandas possui duas estruturas de dados principais:
- Series: Array unidimensional com rótulos
- DataFrame: Estrutura tabular 2D (como uma planilha) que pode conter diferentes tipos de dados

In [1]:
import pandas as pd

#criando uma series
s = pd.Series([1, 2, 3, 4])
print(s) #na tela aparece duas colunas sendo a primeira indicando o índice e a segunda indicando o número 

0    1
1    2
2    3
3    4
dtype: int64


In [2]:
import pandas as pd
df = pd.DataFrame({
    'Nome': ['Alice', 'Bob', 'Carlos'],
    'Idade': [25, 30, 20],
    'Cidade': ['Rio de Janeiro', 'Nova Iorque', 'Salvador'] 
})

print(df) #o resultado é similar de uma planilha

     Nome  Idade          Cidade
0   Alice     25  Rio de Janeiro
1     Bob     30     Nova Iorque
2  Carlos     20        Salvador


Também é possivel exportar um dataframe com o:
pd.read_csv('planilha.csv') -> pode ler outros tipos de arquivo 
genericamente: 

pd.read_tipo('arquivo.tipo')

TEM QUE ESTÁ NO MESMO DIRETÓRIO, se não será necessario especificar o caminho

para mostrar apenas as 5 primeiras linhas do DataFrame, utilizamos:
arquivo.head() -> o valor pode ser modificado se inserirmos um número dentro dos parênteses. o número 5 é default

metodo info mostra:
- quantidade de colunas
- numero total de elementos
- índices dos elementos
- nome das colunas
- quantidade de valores não nulos por linha
- tipo do item (int, objeto/string etc etc)

arquivo.info()

In [3]:
import pandas as pd
df = pd.DataFrame({
    'Nome': ['Alice', 'Bob', 'Carlos'],
    'Idade': [25, 30, 20],
    'Cidade': ['Rio de Janeiro', 'Nova Iorque', 'Salvador'] 
})

nome_col = df['Nome']
nome_lin = df.loc[0] #primeira linha

print(nome_col) #nome da coluna e o tipo de dado
print(nome_lin) #traz as informações da linha especificada

0     Alice
1       Bob
2    Carlos
Name: Nome, dtype: object
Nome               Alice
Idade                 25
Cidade    Rio de Janeiro
Name: 0, dtype: object


In [4]:
#criando dataframe a partir de um array

#importando bibliotecas
import pandas as pd
import numpy as np

#criando array/matriz
mat = np.array([[1, 2, 3], [4, 5, 6]])

#transformando matriz em um dataframe

df = pd.DataFrame(mat)
df


0  1  2
0  1  2  3
1  4  5  6

In [5]:
#criando dataframe a partir de um array

#importando bibliotecas
import pandas as pd
import numpy as np

#criando array/matriz
mat = np.array([[1, 2, 3], [4, 5, 6]])

#transformando matriz em um dataframe E NOMEANDO AS COLUNAS

df = pd.DataFrame(mat, columns=['col1', 'col2', 'col3'])
df


col1  col2  col3
0     1     2     3
1     4     5     6

In [8]:
#ADICIONAR NOVAS COLUNAS e depois removendo

import pandas as pd
df = pd.DataFrame({
    'Nome': ['Alice', 'Bob', 'Carlos'],
    'Idade': [25, 30, 20],
    'Cidade': ['Rio de Janeiro', 'Nova Iorque', 'Salvador'] 
})

df['Salário'] = [5000, 6000, 7000]
df.head()

df.drop('Salário', axis=1, inplace=True) #axis=1 indica que estamos removendo 1 coluna e o inplace=True aplica a alteração diretamente no dataframe original
df.head()

Nome  Idade          Cidade
0   Alice     25  Rio de Janeiro
1     Bob     30     Nova Iorque
2  Carlos     20        Salvador

In [9]:
#Filtragem de dados
import pandas as pd
df = pd.DataFrame({
    'Nome': ['Alice', 'Bob', 'Carlos'],
    'Idade': [25, 30, 20],
    'Cidade': ['Rio de Janeiro', 'Nova Iorque', 'Salvador'] 
})

filtro = df['Idade'] > 25
df_filtrado = df[filtro]
print(df_filtrado)

  Nome  Idade       Cidade
1  Bob     30  Nova Iorque
